# Generated by Django 5.0.14 on 2026-03-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='setup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Montagem'),
        ),
        migrations.AddField(
            model_name='event',
            name='teardown_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Desmontagem'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='setup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Montagem'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='teardown_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Desmontagem'),
        ),
    ]
