# Generated by Django 5.0.14 on 2026-04-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_setup_teardown_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Evento (término)'),
        ),
        migrations.AddField(
            model_name='event',
            name='setup_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Montagem (término)'),
        ),
        migrations.AddField(
            model_name='event',
            name='teardown_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Desmontagem (término)'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='event_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Evento (término)'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='setup_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Montagem (término)'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='teardown_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Desmontagem (término)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='setup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Montagem (início)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teardown_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Desmontagem (início)'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='setup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Montagem (início)'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='teardown_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Desmontagem (início)'),
        ),
    ]
