# Generated by Django 5.0.14 on 2026-03-05 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_itemdescription'),
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorderitem',
            options={'ordering': ['service_order', 'section_name', 'id'], 'verbose_name': 'Item da Ordem de Serviço', 'verbose_name_plural': 'Itens da Ordem de Serviço'},
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='budget_item',
            field=models.OneToOneField(blank=True, help_text='Item do orçamento de origem (rastreabilidade)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_item', to='budgets.budgetitem', verbose_name='Item do Orçamento'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='dim_height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='dim_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Comprimento (m)'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='dim_width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Largura (m)'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='measurement',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Metragem / Volume (m³)'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='measurement_unit',
            field=models.CharField(blank=True, choices=[('m', 'metros (m)'), ('m2', 'metros² (m²)'), ('m3', 'metros³ (m³)')], max_length=10, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='section_name',
            field=models.CharField(blank=True, help_text='Nome da seção de agrupamento (copiado do orçamento)', max_length=255, null=True, verbose_name='Seção'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Unitário (kg)'),
        ),
    ]
