# Generated by Django 5.0.14 on 2026-03-05 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_add_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserviceorder',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token único para link público de visualização da OS', verbose_name='Token Público'),
        ),
    ]
