# Generated by Django 5.0.14 on 2026-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0006_add_approved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=15, verbose_name='Status'),
        ),
    ]
