# Generated by Django 5.0.14 on 2026-02-19 16:01

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='original_document',
            field=models.TextField(blank=True, help_text='PDF ou DOC da proposta original', max_length=255, null=True, verbose_name='Documento Original'),
        ),
        migrations.AlterField(
            model_name='project',
            name='original_document',
            field=models.FileField(blank=True, help_text='PDF ou DOC da proposta original', max_length=255, null=True, upload_to=apps.projects.models.project_upload_path, verbose_name='Documento Original'),
        ),
    ]
