# Generated by Django 5.0.14 on 2026-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='status',
            field=models.CharField(choices=[('in_development', 'Em Desenvolvimento'), ('approved', 'Aprovado'), ('in_execution', 'Em Execução')], default='in_development', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_development', 'Em Desenvolvimento'), ('approved', 'Aprovado'), ('in_execution', 'Em Execução')], default='in_development', max_length=20, verbose_name='Status'),
        ),
    ]
