# Generated by Django 5.0.14 on 2026-02-19 19:51

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_contractor_state_registration_contractor_trade_name_and_more'),
        ('projects', '0002_post_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contractors.contractor', verbose_name='Empreiteira Responsável'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contractors.contractor', verbose_name='Empreiteira Responsável'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('in_development', 'Em Desenvolvimento'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('in_execution', 'Em Execução'), ('rejected', 'Rejeitado'), ('completed', 'Concluído')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('in_development', 'Em Desenvolvimento'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('in_execution', 'Em Execução'), ('rejected', 'Rejeitado'), ('completed', 'Concluído')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('file', models.FileField(max_length=500, upload_to=apps.projects.models.project_file_upload_path, verbose_name='Arquivo')),
                ('file_type', models.CharField(choices=[('plant', 'Planta'), ('drawing', 'Desenho Técnico'), ('specification', 'Especificação'), ('contract', 'Contrato'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='Projeto')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Arquivo de Projeto',
                'verbose_name_plural': 'Arquivos de Projeto',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
