# Generated by Django 5.0.14 on 2026-03-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('projects', '0002_alter_historicalproject_status_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='events.event', verbose_name='Evento'),
        ),
    ]
