# Generated by Django 5.0.14 on 2026-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_contractor_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('plant', 'Planta'), ('drawing', 'Desenho Técnico'), ('specification', 'Especificação'), ('contract', 'Contrato'), ('image', 'Imagem'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo'),
        ),
    ]
