# Generated by Django 5.0.14 on 2026-02-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um usuário com este e-mail.'}, help_text='Endereço de e-mail único para login', max_length=254, unique=True, verbose_name='e-mail')),
                ('first_name', models.CharField(max_length=150, verbose_name='primeiro nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='sobrenome')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o usuário ao invés de excluí-lo.', verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite que o usuário acesse o admin.', verbose_name='membro da equipe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('must_change_password', models.BooleanField(default=False, help_text='Força o usuário a alterar a senha no próximo login.', verbose_name='deve alterar senha')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-created_at'],
            },
        ),
    ]
