# Generated by Django 5.0.14 on 2026-02-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Força o usuário a alterar a senha no próximo login.', verbose_name='deve alterar senha'),
        ),
    ]
