# Generated by Django 5.0.14 on 2026-03-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_art_managers_alter_art_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='engineer_crea',
            field=models.CharField(blank=True, help_text='Número de registro no CREA', max_length=50, null=True, verbose_name='CREA do Engenheiro'),
        ),
        migrations.AlterField(
            model_name='art',
            name='engineer_name',
            field=models.CharField(blank=True, help_text='Preenchido manualmente no documento PDF', max_length=255, null=True, verbose_name='Nome do Engenheiro'),
        ),
        migrations.AlterField(
            model_name='historicalart',
            name='engineer_crea',
            field=models.CharField(blank=True, help_text='Número de registro no CREA', max_length=50, null=True, verbose_name='CREA do Engenheiro'),
        ),
        migrations.AlterField(
            model_name='historicalart',
            name='engineer_name',
            field=models.CharField(blank=True, help_text='Preenchido manualmente no documento PDF', max_length=255, null=True, verbose_name='Nome do Engenheiro'),
        ),
    ]
