# Generated by Django 5.0.14 on 2026-03-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_engineer_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='activity_description',
            field=models.TextField(blank=True, help_text='Objeto técnico da contratação', null=True, verbose_name='Descrição da Atividade / Serviço'),
        ),
        migrations.AlterField(
            model_name='art',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Local da Obra / Endereço'),
        ),
        migrations.AlterField(
            model_name='historicalart',
            name='activity_description',
            field=models.TextField(blank=True, help_text='Objeto técnico da contratação', null=True, verbose_name='Descrição da Atividade / Serviço'),
        ),
        migrations.AlterField(
            model_name='historicalart',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Local da Obra / Endereço'),
        ),
    ]
