# Generated by Django 5.0.14 on 2026-04-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_art_budget_link'),
        ('budgets', '0012_alter_budget_status_alter_historicalbudget_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='budget',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='art', to='budgets.budget', verbose_name='Orçamento'),
            preserve_default=False,
        ),
    ]
