# Generated by Django 5.0.14 on 2026-04-11 19:26

import apps.art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_artfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.art.models.art_file_upload_path, verbose_name='Arquivo'),
        ),
    ]
