# Generated by Django 5.0.14 on 2026-04-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_alter_artfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='atividade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='art',
            name='atividade_complemento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento da Atividade'),
        ),
        migrations.AddField(
            model_name='art',
            name='client_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço (Contratado)'),
        ),
        migrations.AddField(
            model_name='art',
            name='client_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade (Contratado)'),
        ),
        migrations.AddField(
            model_name='art',
            name='client_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento (Contratado)'),
        ),
        migrations.AddField(
            model_name='art',
            name='client_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro (Contratado)'),
        ),
        migrations.AddField(
            model_name='art',
            name='client_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° (Contratado)'),
        ),
        migrations.AddField(
            model_name='art',
            name='client_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF (Contratado)'),
        ),
        migrations.AddField(
            model_name='art',
            name='client_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP (Contratado)'),
        ),
        migrations.AddField(
            model_name='art',
            name='nivel_atuacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nível de Atuação'),
        ),
        migrations.AddField(
            model_name='art',
            name='obra_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço (Obra)'),
        ),
        migrations.AddField(
            model_name='art',
            name='obra_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade (Obra)'),
        ),
        migrations.AddField(
            model_name='art',
            name='obra_complement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento (Obra)'),
        ),
        migrations.AddField(
            model_name='art',
            name='obra_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro (Obra)'),
        ),
        migrations.AddField(
            model_name='art',
            name='obra_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° (Obra)'),
        ),
        migrations.AddField(
            model_name='art',
            name='obra_servico',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Obra / Serviço'),
        ),
        migrations.AddField(
            model_name='art',
            name='obra_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF (Obra)'),
        ),
        migrations.AddField(
            model_name='art',
            name='obra_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP (Obra)'),
        ),
        migrations.AddField(
            model_name='art',
            name='tipo_contratante',
            field=models.CharField(blank=True, choices=[('pf_privado', 'Pessoa Física de Direito Privado'), ('pj_privado', 'Pessoa Jurídica de Direito Privado'), ('pf_publico', 'Pessoa Física de Direito Público'), ('pj_publico', 'Pessoa Jurídica de Direito Público')], max_length=20, null=True, verbose_name='Tipo de Contratante'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='atividade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='atividade_complemento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento da Atividade'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='client_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço (Contratado)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='client_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade (Contratado)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='client_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento (Contratado)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='client_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro (Contratado)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='client_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° (Contratado)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='client_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF (Contratado)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='client_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP (Contratado)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='nivel_atuacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nível de Atuação'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='obra_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço (Obra)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='obra_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade (Obra)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='obra_complement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento (Obra)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='obra_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro (Obra)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='obra_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° (Obra)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='obra_servico',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Obra / Serviço'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='obra_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF (Obra)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='obra_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP (Obra)'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='tipo_contratante',
            field=models.CharField(blank=True, choices=[('pf_privado', 'Pessoa Física de Direito Privado'), ('pj_privado', 'Pessoa Jurídica de Direito Privado'), ('pf_publico', 'Pessoa Física de Direito Público'), ('pj_publico', 'Pessoa Jurídica de Direito Público')], max_length=20, null=True, verbose_name='Tipo de Contratante'),
        ),
        migrations.AlterField(
            model_name='art',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Local da Obra / Endereço (legado)'),
        ),
        migrations.AlterField(
            model_name='historicalart',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Local da Obra / Endereço (legado)'),
        ),
    ]
