# Generated by Django 5.0.14 on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


def forward_copy_art_link(apps, schema_editor):
    ART = apps.get_model('art', 'ART')
    HistoricalART = apps.get_model('art', 'HistoricalART')
    ServiceOrder = apps.get_model('service_orders', 'ServiceOrder')

    for art in ART._base_manager.all():
        if getattr(art, 'service_order_id', None):
            continue

        budget_id = getattr(art, 'budget_id', None)
        if not budget_id:
            continue

        service_order = ServiceOrder._base_manager.filter(budget_id=budget_id).first()
        if not service_order:
            service_order = ServiceOrder._base_manager.create(
                budget_id=budget_id,
                status='pending',
                created_by_id=getattr(art, 'created_by_id', None),
                updated_by_id=getattr(art, 'updated_by_id', None),
            )

        art.service_order_id = service_order.id
        art.save(update_fields=['service_order'])

    for historical_art in HistoricalART._base_manager.filter(service_order_id__isnull=True).exclude(budget_id__isnull=True):
        service_order = ServiceOrder._base_manager.filter(budget_id=historical_art.budget_id).first()
        if service_order:
            historical_art.service_order_id = service_order.id
            historical_art.save(update_fields=['service_order'])


def backward_copy_art_link(apps, schema_editor):
    ART = apps.get_model('art', 'ART')
    HistoricalART = apps.get_model('art', 'HistoricalART')

    for art in ART._base_manager.filter(budget_id__isnull=True).exclude(service_order_id__isnull=True):
        if art.service_order_id:
            art.budget_id = art.service_order.budget_id
            art.save(update_fields=['budget'])

    for historical_art in HistoricalART._base_manager.filter(budget_id__isnull=True).exclude(service_order_id__isnull=True):
        if historical_art.service_order_id:
            historical_art.budget_id = historical_art.service_order.budget_id
            historical_art.save(update_fields=['budget'])


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0007_alter_historicalserviceorder_status'),
        ('art', '0009_add_art_address_and_activity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='service_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='art', to='service_orders.serviceorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='service_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_orders.serviceorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.RunPython(forward_copy_art_link, backward_copy_art_link),
        migrations.RemoveField(
            model_name='art',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='historicalart',
            name='budget',
        ),
        migrations.AlterField(
            model_name='art',
            name='service_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='art', to='service_orders.serviceorder', verbose_name='Ordem de Serviço'),
        ),
    ]
