# Generated by Django 5.0.14 on 2026-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_art_link_to_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='contratante_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ do Contratante'),
        ),
        migrations.AddField(
            model_name='art',
            name='contratante_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Contratante'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='contratante_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ do Contratante'),
        ),
        migrations.AddField(
            model_name='historicalart',
            name='contratante_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Contratante'),
        ),
    ]
