# Generated by Django 5.0.14 on 2026-02-10 13:13

import apps.proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='original_document',
            field=models.TextField(blank=True, help_text='PDF ou DOC da proposta original', max_length=255, null=True, verbose_name='Documento Original'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='original_document',
            field=models.FileField(blank=True, help_text='PDF ou DOC da proposta original', max_length=255, null=True, upload_to=apps.proposals.models.proposal_upload_path, verbose_name='Documento Original'),
        ),
    ]
