# Generated by Django 5.0.14 on 2026-02-05 14:15

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.documents.models.event_document_upload_path, verbose_name='Arquivo')),
                ('doc_type', models.CharField(choices=[('art', 'ART (Anotação de Responsabilidade Técnica)'), ('insurance', 'Seguro'), ('certificate', 'Certificado'), ('contract', 'Contrato'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Documento')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Documento do Evento',
                'verbose_name_plural': 'Documentos dos Eventos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
