# Generated by Django 5.0.14 on 2026-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreightSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo adicionado independentemente do peso/volume', max_digits=10, verbose_name='Taxa Fixa por Entrega (R$)')),
                ('percentage_on_total', models.DecimalField(decimal_places=2, default=0, help_text='Percentual aplicado sobre o valor total do orçamento (ex: 5.00 = 5%)', max_digits=5, verbose_name='Percentual sobre o Valor Total (%)')),
                ('distance_rate_enabled', models.BooleanField(default=False, verbose_name='Habilitar Frete por Distância')),
                ('distance_rate_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Custo por quilômetro rodado (requer que o orçamento informe a distância)', max_digits=8, verbose_name='Taxa por Km (R$)')),
                ('calculation_mode', models.CharField(choices=[('max', 'Usar o maior valor (peso ou volume)'), ('sum', 'Somar peso e volume'), ('weight', 'Usar apenas peso'), ('volume', 'Usar apenas volume')], default='max', help_text='Como combinar as tabelas de peso e volume', max_length=10, verbose_name='Modo de Cálculo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Frete',
                'verbose_name_plural': 'Configuração de Frete',
            },
        ),
        migrations.CreateModel(
            name='UrgencyMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, help_text='1.00 = sem acréscimo, 1.50 = +50%, 2.00 = 100% a mais', max_digits=5, verbose_name='Multiplicador')),
                ('is_default', models.BooleanField(default=False, help_text='Urgência selecionada por padrão nos orçamentos', verbose_name='Padrão')),
            ],
            options={
                'verbose_name': 'Urgência de Entrega',
                'verbose_name_plural': 'Urgências de Entrega',
                'ordering': ['multiplier'],
            },
        ),
        migrations.CreateModel(
            name='VolumeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Até 1 m³, De 1 a 5 m³', max_length=100, verbose_name='Descrição')),
                ('min_volume', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Volume Mínimo (m³)')),
                ('max_volume', models.DecimalField(blank=True, decimal_places=3, help_text='Deixe em branco para "acima de X"', max_digits=10, null=True, verbose_name='Volume Máximo (m³)')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor (R$)')),
                ('rate_type', models.CharField(choices=[('fixed', 'Valor fixo para a faixa'), ('per_m3', 'R$ por m³ adicional')], default='fixed', max_length=10, verbose_name='Tipo de Valor')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Faixa de Volume',
                'verbose_name_plural': 'Faixas de Volume',
                'ordering': ['order', 'min_volume'],
            },
        ),
        migrations.CreateModel(
            name='WeightRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Até 50 kg, De 51 a 100 kg', max_length=100, verbose_name='Descrição')),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso Mínimo (kg)')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para "acima de X"', max_digits=10, null=True, verbose_name='Peso Máximo (kg)')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor (R$)')),
                ('rate_type', models.CharField(choices=[('fixed', 'Valor fixo para a faixa'), ('per_ton', 'R$ por tonelada')], default='fixed', max_length=10, verbose_name='Tipo de Valor')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Faixa de Peso',
                'verbose_name_plural': 'Faixas de Peso',
                'ordering': ['order', 'min_weight'],
            },
        ),
    ]
