# Generated by Django 5.0.14 on 2026-02-27 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_approval_tokens(apps, schema_editor):
    Budget = apps.get_model("budgets", "Budget")
    for budget in Budget.objects.filter(approval_token__isnull=True):
        budget.approval_token = uuid.uuid4()
        budget.save(update_fields=["approval_token"])
    seen = set()
    for budget in Budget.objects.all().order_by("id"):
        if budget.approval_token in seen:
            budget.approval_token = uuid.uuid4()
            budget.save(update_fields=["approval_token"])
        seen.add(budget.approval_token)


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="approval_status",
            field=models.CharField(choices=[("pending", "Pendente"), ("approved", "Aprovado pelo Cliente"), ("rejected", "Rejeitado pelo Cliente")], default="pending", max_length=20, verbose_name="Status de Aprovação"),
        ),
        migrations.AddField(
            model_name="budget",
            name="approval_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, help_text="Token único para link público de aprovação", verbose_name="Token de Aprovação"),
        ),
        migrations.RunPython(populate_approval_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="budget",
            name="approval_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, help_text="Token único para link público de aprovação", verbose_name="Token de Aprovação"),
        ),
        migrations.AddField(
            model_name="budget",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data de Aprovação"),
        ),
        migrations.AddField(
            model_name="budget",
            name="client_notes",
            field=models.TextField(blank=True, help_text="Comentários do cliente na aprovação", null=True, verbose_name="Observações do Cliente"),
        ),
        migrations.AddField(
            model_name="budget",
            name="freight_cost",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Calculado automaticamente ou informado manualmente", max_digits=10, null=True, verbose_name="Custo de Frete (R$)"),
        ),
        migrations.AddField(
            model_name="budget",
            name="freight_distance_km",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Usado no cálculo por distância (opcional)", max_digits=8, null=True, verbose_name="Distância para Entrega (km)"),
        ),
        migrations.AddField(
            model_name="budget",
            name="freight_urgency",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="budgets", to="logistics.urgencymultiplier", verbose_name="Urgência de Entrega"),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="dim_height",
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Altura unitária em metros", max_digits=8, null=True, verbose_name="Altura (m)"),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="dim_length",
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Comprimento unitário em metros", max_digits=8, null=True, verbose_name="Comprimento (m)"),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="dim_width",
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Largura unitária em metros", max_digits=8, null=True, verbose_name="Largura (m)"),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="is_approved",
            field=models.BooleanField(default=True, help_text="Item selecionado para aprovação pelo cliente", verbose_name="Aprovado pelo Cliente"),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="measurement",
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Preenchido automaticamente a partir das dimensões, ou manualmente", max_digits=10, null=True, verbose_name="Metragem / Volume (m³)"),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="measurement_unit",
            field=models.CharField(blank=True, choices=[("m", "metros (m)"), ("m2", "metros² (m²)"), ("m3", "metros³ (m³)")], help_text="Tipo de unidade de medida", max_length=10, null=True, verbose_name="Unidade de Medida"),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="weight_kg",
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Peso total do item ou unitário × quantidade", max_digits=10, null=True, verbose_name="Peso (kg)"),
        ),
    ]
