# Generated by Django 5.0.14 on 2026-02-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'ordering': ['budget', 'id'], 'verbose_name': 'Item do Orçamento', 'verbose_name_plural': 'Itens do Orçamento'},
        ),
        migrations.AlterModelOptions(
            name='historicalbudget',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Orçamento', 'verbose_name_plural': 'historical Orçamentos'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='is_selected',
            field=models.BooleanField(default=False, help_text='Orçamento escolhido pelo cliente', verbose_name='Selecionado'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(help_text='Nome identificador deste orçamento', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budget', verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Total'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='is_selected',
            field=models.BooleanField(default=False, help_text='Orçamento escolhido pelo cliente', verbose_name='Selecionado'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='name',
            field=models.CharField(help_text='Nome identificador deste orçamento', max_length=255, verbose_name='Nome'),
        ),
    ]
