# Generated by Django 5.0.14 on 2026-02-27 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_approval_status_budget_approval_token_and_more'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso por unidade em quilogramas', max_digits=10, null=True, verbose_name='Peso Unitário (kg)'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado pelo Cliente'), ('rejected', 'Rejeitado pelo Cliente')], default='pending', max_length=20, verbose_name='Status de Aprovação'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='approval_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token único para link público de aprovação', verbose_name='Token de Aprovação'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='client_notes',
            field=models.TextField(blank=True, help_text='Comentários do cliente na aprovação', null=True, verbose_name='Observações do Cliente'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente ou informado manualmente', max_digits=10, null=True, verbose_name='Custo de Frete (R$)'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='freight_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usado no cálculo por distância (opcional)', max_digits=8, null=True, verbose_name='Distância para Entrega (km)'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='freight_urgency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.urgencymultiplier', verbose_name='Urgência de Entrega'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantidade de unidades', verbose_name='Quantidade'),
        ),
    ]
