# Generated by Django 5.0.14 on 2026-03-02 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budgetsection_budgetitem_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome curto exibido no seletor (ex.: "Painel modulado 3×3")', max_length=255, verbose_name='Título')),
                ('body', models.TextField(blank=True, help_text='Texto completo que será copiado para o item do orçamento', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Descrição de Item',
                'verbose_name_plural': 'Descrições de Itens',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='budgetsection',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Seção do Orçamento', 'verbose_name_plural': 'Seções do Orçamento'},
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Seção a qual este item pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='budgets.budgetsection', verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='budgetsection',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='budgets.budget', verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='budgetsection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Posição da seção dentro do orçamento', verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='budgetsection',
            name='title',
            field=models.CharField(help_text='Nome da seção do orçamento', max_length=255, verbose_name='Título da Seção'),
        ),
    ]
