# Generated by Django 5.0.14 on 2026-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_itemdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='freight_included',
            field=models.BooleanField(default=None, help_text='Cliente optou por incluir o frete no total aprovado', null=True, verbose_name='Frete Incluído'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='freight_included',
            field=models.BooleanField(default=None, help_text='Cliente optou por incluir o frete no total aprovado', null=True, verbose_name='Frete Incluído'),
        ),
    ]
