# Generated by Django 5.0.14 on 2026-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_add_freight_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='include_fiscal_charges',
            field=models.BooleanField(default=False, help_text='Aplica 17% de encargos fiscais sobre os itens do orçamento', verbose_name='Incluir Encargos Fiscais'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='include_fiscal_charges',
            field=models.BooleanField(default=False, help_text='Aplica 17% de encargos fiscais sobre os itens do orçamento', verbose_name='Incluir Encargos Fiscais'),
        ),
    ]
