# Generated by Django 5.0.14 on 2026-03-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_budgetitem_subitems_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='extra_charges',
            field=models.JSONField(blank=True, default=dict, help_text='Apoio, mão de obra extra, documentação e taxas da feira', verbose_name='Encargos Adicionais'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='extra_charges',
            field=models.JSONField(blank=True, default=dict, help_text='Apoio, mão de obra extra, documentação e taxas da feira', verbose_name='Encargos Adicionais'),
        ),
    ]
