# Generated by Django 5.0.14 on 2026-03-30 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_add_extra_charges_to_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='description_ref',
            field=models.ForeignKey(blank=True, help_text='Referência à descrição padrão usada (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='budgets.itemdescription', verbose_name='Descrição da biblioteca'),
        ),
    ]
