# Generated by Django 5.0.14 on 2026-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_add_description_ref_to_budget_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Em andamento'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='status',
            field=models.CharField(choices=[('draft', 'Em andamento'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='draft', max_length=10, verbose_name='Status'),
        ),
    ]
