# Generated by Django 5.0.14 on 2026-04-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_alter_budget_status_alter_historicalbudget_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Em andamento'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('confirmed', 'Confirmado')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='status',
            field=models.CharField(choices=[('draft', 'Em andamento'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('confirmed', 'Confirmado')], default='draft', max_length=10, verbose_name='Status'),
        ),
    ]
