# Generated by Django 5.0.14 on 2026-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0013_add_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='include_fiscal',
            field=models.BooleanField(default=False, help_text='Aplica 17% de encargos fiscais sobre o total deste item', verbose_name='Encargos Fiscais (17%)'),
        ),
    ]
