# Generated by Django 5.0.14 on 2026-04-11 19:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_budgetitem_include_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='discount_type',
            field=models.CharField(choices=[('none', 'Sem desconto'), ('percent', 'Percentual (%)'), ('value', 'Valor (R$)')], default='none', help_text='Define se o desconto será em percentual ou valor fixo', max_length=10, verbose_name='Tipo de Desconto'),
        ),
        migrations.AddField(
            model_name='budget',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentual (%) ou valor fixo (R$), conforme o tipo selecionado', max_digits=10, verbose_name='Valor do Desconto'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='discount_type',
            field=models.CharField(choices=[('none', 'Sem desconto'), ('percent', 'Percentual (%)'), ('value', 'Valor (R$)')], default='none', help_text='Define se o desconto será em percentual ou valor fixo', max_length=10, verbose_name='Tipo de Desconto'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentual (%) ou valor fixo (R$), conforme o tipo selecionado', max_digits=10, verbose_name='Valor do Desconto'),
        ),
    ]
