# Generated by Django 5.0.14 on 2026-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0015_budget_discount_type_budget_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='payment_info',
            field=models.TextField(blank=True, default='', help_text='Bloco exibido antes das observações no documento público', verbose_name='Informações de Pagamento'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='payment_info',
            field=models.TextField(blank=True, default='', help_text='Bloco exibido antes das observações no documento público', verbose_name='Informações de Pagamento'),
        ),
        migrations.CreateModel(
            name='PaymentInfoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome curto exibido no seletor (ex.: "Dados bancários padrão")', max_length=255, verbose_name='Título')),
                ('body', models.TextField(blank=True, help_text='Texto completo que será copiado para o orçamento', verbose_name='Informações de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Informação de Pagamento',
                'verbose_name_plural': 'Informações de Pagamento',
                'ordering': ['title'],
            },
        ),
    ]
