# Generated by Django 5.0.14 on 2026-05-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0019_budgetversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviado'), ('rejected', 'Rejeitado'), ('confirmed', 'Confirmado')], default='sent', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviado'), ('rejected', 'Rejeitado'), ('confirmed', 'Confirmado')], default='sent', max_length=10, verbose_name='Status'),
        ),
    ]
