# Generated by Django 5.0.14 on 2026-05-11 16:42

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    """Migrate existing draft and approved statuses to new values."""
    Budget = apps.get_model('budgets', 'Budget')
    
    # Migrate draft → sent
    Budget.objects.filter(status='draft').update(status='sent')
    
    # Migrate approved → confirmed
    Budget.objects.filter(status='approved').update(status='confirmed')


def reverse_migrate(apps, schema_editor):
    """Reverse the migration (for rollback)."""
    Budget = apps.get_model('budgets', 'Budget')
    
    # Reverse: confirmed → approved (only if we can identify them)
    # Note: We can't safely reverse sent → draft since we don't know which sent were originally draft
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_remove_draft_approved_status'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_migrate),
    ]
