# Generated by Django 5.0.14 on 2026-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0024_budgetitem_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Confirmado pelo Cliente'), ('rejected', 'Rejeitado pelo Cliente')], default='pending', max_length=20, verbose_name='Status de Aprovação'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Item selecionado para confirmação pelo cliente', verbose_name='Confirmado pelo Cliente'),
        ),
        migrations.AlterField(
            model_name='budgetnotification',
            name='action',
            field=models.CharField(choices=[('approved', 'Confirmado'), ('rejected', 'Rejeitado')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Confirmado pelo Cliente'), ('rejected', 'Rejeitado pelo Cliente')], default='pending', max_length=20, verbose_name='Status de Aprovação'),
        ),
    ]
