# Generated by Django 5.0.14 on 2026-02-19 17:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_add_new_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # deleted/deleted_by_cascade/created_at/updated_at already exist in DB
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='contractor',
                    name='deleted',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                migrations.AddField(
                    model_name='contractor',
                    name='deleted_by_cascade',
                    field=models.BooleanField(default=False, editable=False),
                ),
                migrations.AlterField(
                    model_name='contractor',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
                ),
                migrations.AlterField(
                    model_name='contractor',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalContractor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empreiteira')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('legal_representative', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsavel Legal')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('address_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero')),
                ('address_complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('address_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('bank_agency', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agencia')),
                ('bank_account', models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta')),
                ('bank_account_type', models.CharField(blank=True, choices=[('corrente','Corrente'),('poupanca','Poupanca')], max_length=20, null=True, verbose_name='Tipo de Conta')),
                ('bank_pix_key', models.CharField(blank=True, max_length=150, null=True, verbose_name='Chave PIX')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Certificacoes')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observacoes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+','Created'),('~','Changed'),('-','Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'historical Empreiteira',
                'verbose_name_plural': 'historical Empreiteiras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
