# Generated by Django 5.0.14 on 2026-03-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_contractormembernrfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContractorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_members', to='contractors.eventcontractor', verbose_name='Vínculo Empreiteira-Evento')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='contractors.contractormember', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Membro em Evento',
                'verbose_name_plural': 'Membros em Eventos',
                'ordering': ['member__name'],
                'unique_together': {('assignment', 'member')},
            },
        ),
    ]
