# Generated by Django 5.0.14 on 2026-02-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_contractor_deleted_contractor_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='state_registration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='trade_name',
            field=models.CharField(blank=True, help_text='Nome fantasia da empreiteira', max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='address_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='address_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='aso_exam_type',
            field=models.CharField(blank=True, choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('retorno', 'Retorno ao Trabalho'), ('mudanca_funcao', 'Mudança de Função'), ('demissional', 'Demissional')], max_length=20, null=True, verbose_name='Tipo de Exame ASO'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='aso_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade do ASO'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='aso_file',
            field=models.FileField(blank=True, null=True, upload_to='contractor_members/aso/', verbose_name='ASO (upload)'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='aso_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão do ASO'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='aso_number',
            field=models.CharField(blank=True, help_text='Número do Atestado de Saúde Ocupacional', max_length=50, null=True, verbose_name='Número ASO'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='cpf',
            field=models.CharField(blank=True, help_text='Ex: 000.000.000-00', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone de Emergência'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tempo de Experiência (anos)'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='nr_certificate_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade do Certificado NR'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='nr_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='contractor_members/nr_certificates/', verbose_name='Certificado NR (upload)'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='nr_number',
            field=models.CharField(blank=True, help_text='Ex: NR-10, NR-35, NR-33', max_length=10, null=True, verbose_name='Número NR'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contractor_members/photos/', verbose_name='Foto do Profissional'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='rg',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='contractormember',
            name='specialty',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='historicalcontractor',
            name='state_registration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='historicalcontractor',
            name='trade_name',
            field=models.CharField(blank=True, help_text='Nome fantasia da empreiteira', max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(help_text='Razão social da empreiteira', max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='contractormember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='contractormember',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='contractormember',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Ex: Técnico de Som, Iluminador, Eletricista, etc.', max_length=100, verbose_name='Função/Cargo'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='address_state',
            field=models.CharField(blank=True, help_text='Sigla do estado (ex: SP)', max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='bank_agency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='certifications',
            field=models.TextField(blank=True, help_text='Descreva as certificações, alvarás e documentações da empresa', null=True, verbose_name='Certificações e Alvarás'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Ex: 00.000.000/0001-00', max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='legal_representative',
            field=models.CharField(blank=True, help_text='Nome do responsável legal pela empresa', max_length=255, null=True, verbose_name='Responsável Legal'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='name',
            field=models.CharField(help_text='Razão social da empreiteira', max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
