# Generated by Django 5.0.14 on 2026-03-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ', max_length=18, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=4, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='document_number',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ', max_length=18, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=4, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
