# Generated by Django 5.0.14 on 2026-05-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_historicalclient_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
