# Generated by Django 5.0.14 on 2026-02-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('role', models.CharField(help_text='Ex: Técnico de Som, Iluminador, etc.', max_length=100, verbose_name='Função')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='events.event', verbose_name='Evento')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='teams.teammember', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Equipe do Evento',
                'verbose_name_plural': 'Equipes dos Eventos',
                'ordering': ['event', 'member'],
                'unique_together': {('event', 'member')},
            },
        ),
    ]
