# Generated by Django 5.0.14 on 2026-03-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltechnicalvisit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Levantamento de Informações', 'verbose_name_plural': 'historical Levantamentos de Informações'},
        ),
        migrations.AlterModelOptions(
            name='technicalvisit',
            options={'ordering': ['-visit_date'], 'verbose_name': 'Levantamento de Informações', 'verbose_name_plural': 'Levantamentos de Informações'},
        ),
    ]
